PDF_DB_NAME = "grobid_scipdf"
PDF_DB_DIR = "pdf_db"
PDF_DB_CACHE_PATH = f"{PDF_DB_DIR}/{PDF_DB_NAME}.pkl"
FAISS_INDEX_DIR = "faiss_index"
RAW_PDF_DIR = "content"
MODEL_DIR = "models/chatglm-6b-int4"
EMBEDDING_MODEL_ZH_DIR = "embeddings/text2vec-large-chinese"
TF_EMBEDDING_MODEL_URL = "https://hub.tensorflow.google.cn/google/universal-sentence-encoder/4"
